### ISSUE TITLE
MDC?

### ISSUE THREAD

**Issue by ruoqizzz** [MDCHAMP/nonlinear_baselines_archived#1]
Hi,

Can I ask what is MDC? Is this a Python library?

**Comment by MDCHAMP** [comment]
Hi, the module `mdc` is a local development library (a subset of which is copied to `src` in this repo) and as such should not have been left in the script. I have changed the imports to point at the correct location. Hope this helps! 

Let me know if you have any other issues. 

Max

**Comment by ruoqizzz** [comment]
Hi Max,

Thanks for the updates. There are remaining 'MDC' in 
```
data.py
src/jacks/jeep.py
src/jacls/opt.py
src/polys.py
```

You probably also wanna update these.

Best
Ruoqi

**Comment by MDCHAMP** [comment]
Good spots! These are now fixed!
